import { TaskType } from '@/common/models/task';

export const tasks: TaskType[] = [
  {
    id: '1',
    title: 'Tarefa de história',
    creator: 'Prof.ª Eliane',
    viewed: false,
    dueDate: new Date(2024, new Date().getMonth(), 5),
    createdAt: new Date(2024, 4, 1),
    groups: ['3 EM'],
    tags: ['História'],
    files: [],
    content:
      'Tarefa de história destinada aos alunos do 3º ano do ensino médio, cujo o objetivo é aprender mais sobre a história do Japão e seu contexto socioeconômico.',
    finished: false,
  },
  {
    id: '2',
    title: 'Trabalho de Matemática',
    creator: 'Prof. Carlos',
    viewed: false,
    dueDate: new Date(2024, new Date().getMonth(), 10),
    createdAt: new Date(2024, 4, 2),
    groups: ['2 EM'],
    tags: ['Matemática'],
    files: [],
    content: 'Resolver uma série de exercícios sobre funções quadráticas.',
    finished: false,
  },
  {
    id: '3',
    title: 'Relatório de Ciências',
    creator: 'Prof.ª Marta',
    viewed: false,
    dueDate: new Date(2024, new Date().getMonth(), 15),
    createdAt: new Date(2024, 4, 3),
    groups: ['1 EM'],
    tags: ['Ciências'],
    files: [],
    content: 'Elaborar um relatório sobre os resultados do experimento de química feito em laboratório.',
    finished: false,
  },
  {
    id: '4',
    title: 'Ensaio de Português',
    creator: 'Prof.ª Helena',
    viewed: false,
    dueDate: new Date(2024, new Date().getMonth(), 20),
    createdAt: new Date(2024, 4, 5),
    groups: ['3 EM'],
    tags: ['Português'],
    files: [],
    content:
      "Escrever um ensaio crítico sobre 'Memórias Póstumas de Brás Cubas', destacando as principais correntes filosóficas presentes na obra.",
    finished: false,
  },
  {
    id: '5',
    title: 'Projeto de Arte',
    creator: 'Prof.ª Lígia',
    viewed: false,
    dueDate: new Date(2024, new Date().getMonth(), 25),
    createdAt: new Date(2024, 4, 6),
    groups: ['2 EM'],
    tags: ['Arte'],
    files: [],
    content: 'Criar uma composição artística baseada nas técnicas estudadas de pintura surrealista.',
    finished: false,
  },
  {
    id: '6',
    title: 'Pesquisa de Geografia',
    creator: 'Prof. Roberto',
    viewed: false,
    dueDate: new Date(2024, new Date().getMonth(), 30),
    createdAt: new Date(2024, 4, 7),
    groups: ['1 EM'],
    tags: ['Geografia'],
    files: [],
    content: 'Realizar uma pesquisa sobre os impactos das mudanças climáticas nos diferentes continentes.',
    finished: false,
  },
  {
    id: '7',
    title: 'Pesquisa de Geografia',
    creator: 'Prof. Roberto',
    viewed: false,
    dueDate: new Date(2024, new Date().getMonth(), 30),
    createdAt: new Date(2024, 4, 7),
    groups: ['1 EM'],
    tags: ['Geografia'],
    files: [],
    content: 'Realizar uma pesquisa sobre os impactos das mudanças climáticas nos diferentes continentes.',
    finished: true,
  },
];
